### ISSUE TITLE
misspelled file name

### ISSUE THREAD

**Issue by gzahn** [cxli233/Online_R_learning#4]
Didn't want to open a pull request for this, but...

In 12_Logistic_regression.knit.md (line 64) 
"SYBR_Green.txt" should be "SYBR_green.txt" 
to match capitalization in the actual file name so it can knit properly.

Thanks!

**Comment by cxli233** [comment]
Fixed typo. Thank you for letting me know. 

`qPCR <- read_delim("../data/SYBR_green.txt", delim = "\t", col_types = cols())`
